# Generated by Django 4.0.4 on 2022-04-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateCreation'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
